services:
  # --- x86_64 Linux PC Setup (Direct Hardware Access & Shared Memory) ---
  g1-dev-linux:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: g1-humble-dev:latest
    container_name: g1_dev_linux
    entrypoint: ["/usr/local/bin/g1-entrypoint.sh"]
    network_mode: host                         # Shares host network namespace directly
    privileged: true                           # Grants root-level access for physical USB/Ethernet
    ipc: host                                  # Shares the host's IPC namespace for Zero-Copy /dev/shm
    environment:
      - DISPLAY=${DISPLAY:-}                 # Graphical UI forwarding
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp  # Direct CycloneDDS integration for physical robot
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw       # Mounts X11 server sockets
      - /dev/shm:/dev/shm:rw                   # Zero-copy memory map
      - .:/workspace                           # Mounts workspace directory
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

  # --- Apple Silicon macOS Setup (Virtual Machine Bridge via Zenoh TCP) ---
  g1-dev-mac:
    platform: linux/arm64
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: g1-humble-dev:latest
    container_name: g1_dev_mac
    network_mode: host                         # Shares host network namespace directly
    shm_size: '512mb'                          # Allocated shared memory inside macOS VM
    entrypoint: ["/usr/local/bin/g1-entrypoint.sh"]
    command: [ "/bin/bash" ]
    environment:
      - DISPLAY=${MAC_DISPLAY:-}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///workspace/config/cyclonedds.xml
    volumes:
      - .:/workspace                           # Mounts workspace directory
    stdin_open: true
    tty: true

  g1_simulator:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    networks:
      - g1_sim_net
    environment:
      - CYCLONEDDS_URI=file:///workspace/config/cyclonedds_local.xml
    volumes:
      - ./src:/workspace/src
      - ./config:/workspace/config
    entrypoint: ["/usr/local/bin/g1-entrypoint.sh"]
    command: python3 /workspace/src/g1_cognitive_nodes/g1_cognitive_nodes/g1_mock_publisher.py

  g1_telemetry_listener:
      build:
        context: .
        dockerfile: .devcontainer/Dockerfile
      networks:
        - g1_sim_net
      environment:
        - CYCLONEDDS_URI=file:///workspace/config/cyclonedds_local.xml
      volumes:
        - ./src:/workspace/src
        - ./config:/workspace/config
      entrypoint: ["/usr/local/bin/g1-entrypoint.sh"]

networks:
   g1_sim_net:
     driver: bridge
